# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html#common-application-properties
management:
  server:
     port: 8380
     servlet:
        context-path: /
  endpoint:
    health:
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: false
    prometheus:
      enabled: true
  endpoints:
    web:
      path-mapping:
        prometheus: metrics
      base-path: /_/
      exposure:
        include: "*"

# 
# Configuracao padrao
#


spring:

  profiles: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/escola-query
    username: postgres
    password: 1234567
  
  cloud:
    stream:
      defaultBinder: rabbit1
      bindings:
       escola-input-events:       
         destination: escola-exchange
         group: escola-query
       tjf-messaging-error-input:
          destination: escola-query-errors
          group: escola-query-errors
      rabbit:
        bindings:
          rac-input:
            consumer:
              exchange-type: fanout
      binders:
        rabbit1:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                connection-timeout: 10000
                virtualHost: /
        rabbit2:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                connection-timeout: 10000
                virtualHost: /

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true
        
  flyway:
    enabled: false
    migrate: true
    locations: classpath:db/migration
    # Only TOTVS Tenant (94d73469-6861-46a8-96b3-1abf272e3983)
    schemas: public
    baselineOnMigrate: true
        
server:
  port : 8480